### ISSUE TITLE
Usage???

### ISSUE THREAD

**Issue by SuperZombi** [BUnipendix/PyMhyNetSniffer#1]

**Comment by BUnipendix** [comment]
the code can only be used for a reference because it is incomplete and not good to  be used as a tool.
I prefer you to use [Akebi-PacketSniffer](https://github.com/Akebi-Group/Akebi-PacketSniffer).

**Comment by BUnipendix** [comment]
FinishedParentQuestNotify and FinishedParentQuestUpdateNotify has a list of ParentQuest field
![图片](https://user-images.githubusercontent.com/100204822/193108819-a96cae81-3744-47eb-827d-e93083f29ea0.png)
And key is in the Unk2700_KHDDIJNOICK field.
![图片](https://user-images.githubusercontent.com/100204822/193109568-f7a91d00-6a8a-4143-8a58-dd4c4664103c.png)
